exports.suicideKeywords = [
    "kill myself",
    "kill my self",
    "kill self",
    "kill yourself",
    "seppuku",
    "talon e",
    "commit die",
    "suicide",
    "off myself",
    "off mys",
    "off yourself",
    "end it all",
    "end my life",
    "end your life",
    "take my life",
    "take your life",
    "self harm",
    "self-harm",
    "self delete",
    "unalive myself",
    "unalive yourself",
    "kms",
    " kys",
    "kys",
    "kms",
    "do yourself",
    "do myself",
    "rope yourself",
    "rope myself",
    "rope yourself",
    "rope myself",
    "rope my self",
    "rope my self",
    "hanging",
    "hang myself",
    "hang yourself",
    "end it",
    "end myself",
    "end yourself",
    "delete myself",
    "delete yourself",
    "not want to live",
    "dont want to live",
    "don't want to live",
    "want to die",
    "wanna die",
    "wish i was dead",
    "wish i were dead",
    "wish you were dead",
    "better off dead",
    "better off without me",
    "world be better without me",
    "everyone be better without me",
    "no point in living",
    "no reason to live",
    "nothing to live for",
    "give up on life",
    "give up on living",
    "stop existing",
    "cease to exist",
    "not exist anymore",
    "disappear forever",
    "make it stop",
    "make the pain stop",
    "end the pain",
    "end my suffering",
    "end your suffering",
    "can't go on",
    "cant go on",
    "can't take it anymore",
    "cant take it anymore",
    "can't handle it",
    "cant handle it",
    "too much to handle",
    "not worth living",
    "life not worth living",
    "not worth it anymore"
];

exports.inspirationalPeople = [
    "Gandhi",
    "Lebron James",
    "Kobe Bryant",
    "Notch",
    "Jesus",
    "Colonel Sanders",
    "the Wright Brothers",
    "Albert Einstein",
    "Nelson Mandela",
    "Martin Luther King Jr.",
    "Mother Teresa",
    "Helen Keller",
    "Stephen Hawking",
    "Rosa Parks",
    "Walt Disney",
    "Steve Jobs",
    "Bill Gates",
    "Oprah Winfrey",
    "Michael Jordan",
    "Muhammad Ali",
    "Thomas Edison",
    "Marie Curie",
    "Leonardo da Vinci",
    "Pablo Picasso",
    "Vincent van Gogh",
    "William Shakespeare",
    "Charles Darwin",
    "Isaac Newton",
    "Nikola Tesla",
    "Henry Ford",
    "Coco Chanel",
    "Audrey Hepburn",
    "Steve Jobs",
    "Logan Paul",
    "Spongebob",
    "Mao Zedong",
    "John Cena",
    "JFK",
    "Abraham Lincoln",
];
