exports.suicideKeywords = [
    "kill myself",
    "kill my self",
    "kill self",
    "kill yourself",
    "seppuku",
    "talon e",
    "commit die",
    "suicide",
    "off myself",
    "off mys",
    "off yourself",
    "end it all",
    "end my life",
    "end your life",
    "take my life",
    "take your life",
    "self harm",
    "self-harm",
    "self delete",
    "unalive myself",
    "unalive yourself",
    "kms",
    " kys",
    "kys",
    "kms",
    "do it",
    "do yourself",
    "do myself",
    "rope",
    "hanging",
    "hang myself",
    "hang yourself",
    "jump off",
    "jump from",
    "jump to",
    "end it",
    "end myself",
    "end yourself"
];

exports.inspirationalPeople = [
    "Gandhi",
    "Lebron James",
    "Kobe Bryant",
    "Notch",
    "Jesus",
    "Colonel Sanders",
    "the Wright Brothers",
    "Albert Einstein",
    "Nelson Mandela",
    "Martin Luther King Jr.",
    "Mother Teresa",
    "Helen Keller",
    "Stephen Hawking",
    "Rosa Parks",
    "Walt Disney",
    "Steve Jobs",
    "Bill Gates",
    "Oprah Winfrey",
    "Michael Jordan",
    "Muhammad Ali",
    "Thomas Edison",
    "Marie Curie",
    "Leonardo da Vinci",
    "Pablo Picasso",
    "Vincent van Gogh",
    "William Shakespeare",
    "Charles Darwin",
    "Isaac Newton",
    "Nikola Tesla",
    "Henry Ford",
    "Coco Chanel",
    "Audrey Hepburn",
    "Steve Jobs",
    "Logan Paul",
    "Spongebob",
    "Mao Zedong",
    "John Cena",
    "JFK",
    "Abraham Lincoln",
];
