exports.clipNames = [
    'winner',
    'ads',
    'fna2 eerie',
    'bruh', 
    'boing',
    'gmod',
    'vine',
    'clash',
    'metalgear',
    'tf2 notif',
    'boing',
    'something in my a',
    'skype disconnect',
    'skype connect',
    'suction',
    'fallout money',
    "fallout rep down",
    "ow my shoulder",
    "you're done",
    "srsly noo",
    "SUIIIII",
    "wowaweewa",
    "league match found",
    "valorant accept",
    "cs accept",
    "my heart"
]
exports.clips = [
    'https://lobfile.com/file/0qDy.mp3',
    'https://lobfile.com/file/E9oa.mp3',
    'https://lobfile.com/file/zylm.mp3',
    'https://lobfile.com/file/NWF0g.mp3',
    'https://lobfile.com/file/nWGC.mp3',
    'https://lobfile.com/file/L005.mp3',
    'https://lobfile.com/file/c617.mp3',
    'https://lobfile.com/file/tDKk.mp3',
    'https://lobfile.com/file/1xCr.mp3',
    'https://lobfile.com/file/0zc1.mp3',
    'https://lobfile.com/file/H9Tr.mp3',
    'https://lobfile.com/file/SZYf.mp3',
    'https://a.pomf.cat/eixmvl.m4a',
    'https://a.pomf.cat/ebxbom.m4a',
    'https://a.pomf.cat/gidfxi.m4a',
    "https://a.pomf.cat/chcrem.m4a",
    "https://a.pomf.cat/nuxskj.m4a",
    "https://a.pomf.cat/kzwcfh.mp3",
    "https://lobfile.com/file/0Lgz.mp3",
    "https://a.pomf.cat/eyjpxw.mp3",
    "https://lobfile.com/file/wDwO.mp3",
    "https://lobfile.com/file/Dfx1.mp3",
    "https://a.pomf.cat/cikbyp.mp3",
    "https://a.pomf.cat/myxgla.mp3",
    "https://a.pomf.cat/vnjunq.mp3",
    "https://lobfile.com/file/Edse.mp3"
]
