exports.clipNames = [
    'winner',
    'ads',
    'fna2 eerie',
    'bruh',
    'boing',
    'gmod',
    'vine',
    'clash',
    'metalgear',
    'tf2 notif',
    'boing',
    'something in my a',
    'my heart',
    'sweet caroline remix',
    'quandale',
    'OHMAHGOD',
    'ENEMY CONTROLS ALL OBJECTIVES',
    'yung lean, bitches come and go',
    'whopper whopper',
    'scooby running',
    'biden boys a liar',
    'rizz',
    'fortnite default dance',
    'spongebob sad',
    'spongebob stinky',
    'spongebob fail',
    'let him cook',
    'you failed',
    'side eye',
    'grant macdonald yo',
    'terraria',
    'my heart i loved her',
    'wowa wee wa its very nice',
    'you will never get this lalala',
    'walt please hear me out'
    
]

exports.clips = [
    'https://lobfile.com/file/0qDy.mp3',
    'https://lobfile.com/file/E9oa.mp3',
    'https://lobfile.com/file/zylm.mp3',
    'https://lobfile.com/file/NWF0g.mp3',
    'https://lobfile.com/file/nWGC.mp3',
    'https://lobfile.com/file/L005.mp3',
    'https://lobfile.com/file/c617.mp3',
    'https://lobfile.com/file/tDKk.mp3',
    'https://lobfile.com/file/1xCr.mp3',
    'https://lobfile.com/file/0zc1.mp3',
    'https://lobfile.com/file/H9Tr.mp3',
    'https://lobfile.com/file/SZYf.mp3',
    'https://lobfile.com/file/Edse.mp3',
    'https://lobfile.com/file/jyUZ.wav',
    'https://lobfile.com/file/fXqg.wav',
    'https://lobfile.com/file/GC8X.wav',
    'https://lithi.pw/file/SacP',
    'https://lobfile.com/file/rz8l.wav',
    'https://lobfile.com/file/exkF.wav',
    'https://lobfile.com/file/zhkU.wav',
    'https://lobfile.com/file/G8b6.wav',
    'https://lobfile.com/file/jXQG.mp3',
    'https://lobfile.com/file/8H2h.mp3',
    'https://lobfile.com/file/nCUO.mp3',
    'https://lobfile.com/file/pBgv.mp3',
    'https://lobfile.com/file/i4Zr.mp3',
    'https://lobfile.com/file/PZAI.mp3',
    'https://lobfile.com/file/oSM9.mp3',
    'https://lobfile.com/file/Siqc.mp3',
    'https://lobfile.com/file/qdoA.mp3',
    'https://lobfile.com/file/w2eI.mp3',
    'https://lobfile.com/file/U5sf.mp3',
    'https://lobfile.com/file/SdIo.mp3',
    'https://lobfile.com/file/w4ou.mp3',
    'https://lobfile.com/file/llM7.mp3'
]